{% set version = "9.0" %}

package:
    name: coloredlogs
    version: {{ version }}

source:
    fn: coloredlogs-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
    sha256: e3b19320bd21bde506444601a71397cf5215f040df06503013697c6261b05de9

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    entry_points:
        - coloredlogs = coloredlogs.cli:main

requirements:
    build:
        - python
        - setuptools
        - humanfriendly >=3.2
    run:
        - python
        - humanfriendly >=3.2
        - colorama  # [win]

test:
    imports:
        - coloredlogs
    commands:
        - coloredlogs --help  # [not osx]

about:
    home: https://coloredlogs.readthedocs.org
    license: MIT
    summary: "Colored terminal output for Python's logging module."

extra:
    recipe-maintainers:
        - ocefpaf
        - andfoy
        - ccordoba12
