{% set version = "10.0" %}

package:
  name: coloredlogs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
  sha256: b869a2dda3fa88154b9dd850e27828d8755bfab5a838a1c97fbc850c6e377c36

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - coloredlogs = coloredlogs.cli:main

requirements:
  host:
    - python
    - pip
    - humanfriendly >=4.7
  run:
    - python
    - humanfriendly >=4.7
    - colorama  # [win]

test:
  imports:
    - coloredlogs
# Probably requires a valid TERM and a pager
#  commands:
#    - coloredlogs --help  # [not osx]

about:
  home: https://coloredlogs.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: Colored terminal output for Python's logging module
  description: |
      The coloredlogs package enables colored terminal output for Python's
      logging module. The ColoredFormatter class uses ANSI escape sequences
      to render logging messages in color. As it uses only standard colors,
      it should work on any UNIX terminal. On Windows, Colorama is
      automatically pulled in as a dependency to enable ANSI escape sequence
      translation.
  dev_url: https://github.com/xolox/python-coloredlogs
  doc_url: https://coloredlogs.readthedocs.io/

extra:
  recipe-maintainers:
    - ocefpaf
    - andfoy
    - ccordoba12
