{% set version = "7.1" %}

package:
    name: coloredlogs
    version: {{ version }}

source:
    fn: coloredlogs-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
    sha256: 4f0f2fdb6245bd8507e4d9eafe2ef3a66536de021cf002cc426e394287bac8b9

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    entry_points:
        - coloredlogs = coloredlogs.cli:main

requirements:
    host:
        - python
        - setuptools
        - humanfriendly >=3.2
    run:
        - python
        - humanfriendly >=3.2
        - colorama  # [win]

test:
    imports:
        - coloredlogs
    commands:
        - coloredlogs --help  # [not osx]

about:
    home: https://coloredlogs.readthedocs.org
    license: MIT
    license_file: LICENSE.txt
    summary: "Colored terminal output for Python's logging module."
    description: |
        The coloredlogs package enables colored terminal output for Python's
        logging module. The ColoredFormatter class uses ANSI escape sequences
        to render logging messages in color. As it uses only standard colors,
        it should work on any UNIX terminal. On Windows, Colorama is
        automatically pulled in as a dependency to enable ANSI escape sequence
        translation.
    dev_url: https://github.com/xolox/python-coloredlogs
    doc_url: https://coloredlogs.readthedocs.io/


extra:
    recipe-maintainers:
        - ocefpaf
        - andfoy
        - ccordoba12
