{% set version = "9.0" %}

package:
    name: coloredlogs
    version: {{ version }}

source:
    fn: coloredlogs-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
    sha256: e3b19320bd21bde506444601a71397cf5215f040df06503013697c6261b05de9

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    entry_points:
        - coloredlogs = coloredlogs.cli:main

requirements:
    host:
        - python
        - setuptools
        - humanfriendly >=4.7
    run:
        - python
        - humanfriendly >=4.7
        - colorama  # [win]

test:
    imports:
        - coloredlogs
        - coloredlogs.converter
    commands:
        # the coloredlogs command needs a interactive terminal on unix which
        # may not be present in the test enviornment
        - coloredlogs --help  # [not unix]

about:
    home: https://coloredlogs.readthedocs.org
    license: MIT
    license_file: LICENSE.txt
    summary: "Colored terminal output for Python's logging module."
    description: |
        The coloredlogs package enables colored terminal output for Python's
        logging module. The ColoredFormatter class uses ANSI escape sequences
        to render logging messages in color. As it uses only standard colors,
        it should work on any UNIX terminal. On Windows, Colorama is
        automatically pulled in as a dependency to enable ANSI escape sequence
        translation.
    dev_url: https://github.com/xolox/python-coloredlogs
    doc_url: https://coloredlogs.readthedocs.io/


extra:
    recipe-maintainers:
        - ocefpaf
        - andfoy
        - ccordoba12
