{% set version = "15.0.1" %}

package:
  name: coloredlogs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
  sha256: 7c991aa71a4577af2f82600d8f8f3a89f936baeaf9b50a9c197da014e5bf16b0
  patches:
    - fix-path-error-on-win.patch  # [win]
    - 0001-Replace-pipes.quote-with-shlex.quote-on-Python-3.patch

build:
  number: 3
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed -v .
  entry_points:
    - coloredlogs = coloredlogs.cli:main

requirements:
  build:
    - patch     # [unix]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - humanfriendly >=9.1
    - colorama  # [win]

test:
  imports:
    - coloredlogs
  requires:
    - pip
  commands:
    - pip check
    - coloredlogs --help

about:
  home: https://coloredlogs.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Colored terminal output for Python's logging module
  description: |
      The coloredlogs package enables colored terminal output for Python's
      logging module. The ColoredFormatter class uses ANSI escape sequences
      to render logging messages in color. As it uses only standard colors,
      it should work on any UNIX terminal. On Windows, Colorama is
      automatically pulled in as a dependency to enable ANSI escape sequence
      translation.
  dev_url: https://github.com/xolox/python-coloredlogs
  doc_url: https://coloredlogs.readthedocs.io/

extra:
  recipe-maintainers:
    - ocefpaf
    - andfoy
    - ccordoba12
