travis:
  secure:
    BINSTAR_TOKEN: WCUYztfwPPkfSZOPfKekamsYIZ2F3i1YrsLixaAD1J3nd9+1ROVnJnXy7HFojb7GMyspgpc2w3ZTKSo6WG8eHNogb/SDT6creepI7jfrux/G/CHJSor3LOA2gLTImQSNcmuQqvFsY3MD4U3DQd4hkfE5GgdAMuKOPoC834dk7IazS9RPEMXJPe4/3gaENDmJAdkdtSwLEYTtm0gRCjSFduwjIVs7+AWBIxhGcaWsJyrHHCWvIoHADJ0N7BHVwOU/Cz8aMxO4v9Y1eb6qIblkGvuaMfFIKipOZnckRQH29907XQ3dJzKv6YOPoJOInBrofDYsR6m2yym1lx7nbR/+S0Inayv8NbX9vNB7qoOrwhfZ7ZK8zyfYa22H6CJhw4/98kJe3b1ks9HjBtKrbk/xRcbL2sr3XOkxOZ6PSThskqrKLB25gizXqbsvcAyMPQxyZHxItj5G9MZX5C7QKc81gfq0nPmPJDGueMMkhVOy8HnngahqKwGH9OImqrLtwQ2IokKkPi6Cxd/qgKQXPr+kYa4QNuYTUJsYUVLxPJsQ2GeKdEQ9UgeJAA6XXbgx7DCSy1L8b6T2x9ttgol5aeHg4zx37XOrAeG8MEjhZhBTGjrV6K8fbfayKQRDs68iMb3Cy3lLv7P3GrqJmyREDYL5kfxlEBAHHOZxUMcBBgHboq8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
