travis:
  secure:
    BINSTAR_TOKEN: nOxnAGDMWLaTwsDEEpyFTb+beHkKNjlvBNF9iZbDdPddg0aNZnHQ0+MjVT3RxJrK1Dw0bF3p5g9huFI8gyK2zDuKADFD72YYafd8+lcIaornZT+o7Xj9eyVDezGCtPDAppZOpEtfT179YUfkwVRqgEfietofGLp1UMzb9PGfkVjYfyT5wav+/v7Z8jlb2lQHS82Ds3HLpNrrcUmlHsAKF/eCCfH9eUSWVNWaHUYgbf7B64PT6Rpc96vyr9HMEXn37El3Qbaoo+bu2ixeQ4WoMbwvW8M5s6xh7TPsNjyDnREYEKeX7iYJDANlu8yAsi6rMDbhNmm9k8mQUVgggO66WdqfigYkArCdq65rypm3CYtsMqEzjAiRLz4X45pyCBku/p7PZIH21puy7G1myAuivQhkXSAedevKSPjBkdHfjVQ4t+LYtKHiW8HEvtWUwVekHInuqoVBvTzr/TRjFLoaHL/3BCffw58iOi7TJKqblLoB4Q0ugHFWk3gkBPoPuhf9cvhmNEFaBIF2+0ihyvDrTwPzPAN4wm4t455BNG0jF2dErC8HtbF5OM6Ltfi1qr1wbM8v1j6QY4lmYVrl1dGNf36cZif54pmIdzswqusTJxkHPcdpd9ZJxUFZc+I0SRGsg7lETEKQ7LhXP/WBLPQTbo+2VPWzDTLWdeoVgknb+UY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
